### ISSUE TITLE
Fails to compile with mono 4.2.1.0 on Debian GNU/Linux

### ISSUE THREAD

**Issue by vedranmiletic** [lachesis/scallion#67]
On Debian unstable with mono from experimental:

```
$ xbuild --version
XBuild Engine Version 12.0
Mono, Version 4.2.1.0
Copyright (C) 2005-2013 Various Mono authors
MSBUILD: error MSBUILD0000: Project file '--version' not found.
$ mono --version
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-3)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen
```

I get the following:

```
XBuild Engine Version 12.0
Mono, Version 4.2.1.0
Copyright (C) 2005-2013 Various Mono authors

Build started 03/12/2015 19:19:40.
__________________________________________________
Project "/home/vedranm/workspace/HPC/scallion/scallion.sln" (default target(s)):
    Target ValidateSolutionConfiguration:
        Building solution configuration "Debug|Any CPU".
    Target Build:
        Project "/home/vedranm/workspace/HPC/scallion/opentk/Source/OpenTK/OpenTK.csproj" (default target(s)):
            Target PrepareForBuild:
                Configuration: Debug Platform: AnyCPU
            Target GenerateSatelliteAssemblies:
            No input files were specified for target GenerateSatelliteAssemblies, skipping.
            Target CoreCompile:
                Tool /usr/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:full /delaysign- /debug+ /keyfile:../../OpenTK.snk /optimize- /out:obj/Debug/OpenTK.dll /resource:obj/Debug/OpenTK.Properties.Resources.resources /resource:obj/Debug/OpenTK.OpenTK.dll.config DisplayDevice.cs DisplayIndex.cs Graphics/GraphicsModeComparer.cs Input/IGamePadDriver.cs Input/IInputDriver2.cs Input/IKeyboardDriver2.cs Input/IMouseDriver2.cs Platform/DisplayDeviceBase.cs Platform/Windows/WinInputBase.cs WindowBorder.cs ContextHandle.cs WindowState.cs IGameWindow.cs GameWindowFlags.cs KeyPressEventArgs.cs AutoGeneratedAttribute.cs NativeWindow.cs DisplayResolution.cs BindingsBase.cs Toolkit.cs FrameEventArgs.cs BlittableValueType.cs GameWindow.cs Minimal.cs Configuration.cs Exceptions.cs INativeWindow.cs Properties/AssemblyInfo.cs Platform/IDisplayDeviceDriver.cs Platform/IWindowInfo.cs Platform/EmbeddedGraphicsContext.cs Platform/PlatformException.cs Platform/IPlatformFactory.cs Platform/Factory.cs Platform/Utilities.cs Platform/INativeGLWindow.cs Platform/DesktopGraphicsContext.cs Platform/Dummy/DummyWindowInfo.cs Platform/Dummy/DummyGLContext.cs Platform/Egl/EglX11PlatformFactory.cs Platform/Egl/EglWinPlatformFactory.cs Platform/Egl/EglGraphicsMode.cs Platform/Egl/EglWindowInfo.cs Platform/Egl/Egl.cs Platform/Egl/EglContext.cs Platform/Egl/EglMacPlatformFactory.cs Platform/MacOS/EventInfo.cs Platform/MacOS/MacOSGraphicsMode.cs Platform/MacOS/MacOSFactory.cs Platform/MacOS/MacOSException.cs Platform/MacOS/MacOSKeyMap.cs Platform/MacOS/CarbonGLNative.cs Platform/MacOS/Application.cs Platform/MacOS/AglContext.cs Platform/MacOS/QuartzDisplayDeviceDriver.cs Platform/MacOS/CarbonInput.cs Platform/MacOS/CarbonWindowInfo.cs Platform/MacOS/CarbonBindings/CarbonAPI.cs Platform/MacOS/CarbonBindings/SpeechChannel.cs Platform/MacOS/CarbonBindings/QuartzDisplayServicesAPI.cs Platform/MacOS/CarbonBindings/MacOSKeys.cs Platform/MacOS/CarbonBindings/Agl.cs Platform/MacOS/CarbonBindings/CoreFoundation.cs Platform/Windows/WinRawKeyboard.cs Platform/Windows/WinFactory.cs Platform/Windows/WinRawInput.cs Platform/Windows/WinRawMouse.cs Platform/Windows/WinDisplayDevice.cs Platform/Windows/API.cs Platform/Windows/WinKeyMap.cs Platform/Windows/WMInput.cs Platform/Windows/WinGLNative.cs Platform/Windows/WinWindowInfo.cs Platform/Windows/WinGLContext.cs Platform/Windows/WinMMJoystick.cs Platform/Windows/WglHelper.cs Platform/Windows/WinGraphicsMode.cs Platform/Windows/Bindings/Wgl.cs Platform/Windows/Bindings/WglDelegates.cs Platform/Windows/Bindings/WglCore.cs Platform/Windows/Bindings/WglEnums.cs Platform/X11/X11WindowInfo.cs Platform/X11/X11Joystick.cs Platform/X11/Functions.cs Platform/X11/GlxHelper.cs Platform/X11/API.cs Platform/X11/X11DisplayDevice.cs Platform/X11/X11GraphicsMode.cs Platform/X11/X11GLNative.cs Platform/X11/X11KeyMap.cs Platform/X11/X11GLContext.cs Platform/X11/Structs.cs Platform/X11/X11Input.cs Platform/X11/X11Factory.cs Platform/X11/Bindings/Glx.cs Graphics/IGraphicsMode.cs Graphics/GraphicsExceptions.cs Graphics/GraphicsErrorException.cs Graphics/Color4.cs Graphics/GraphicsContextVersion.cs Graphics/IGraphicsContext.cs Graphics/GraphicsMode.cs Graphics/GraphicsModeException.cs Graphics/GraphicsContextFlags.cs Graphics/GraphicsContextMissingException.cs Graphics/GraphicsContext.cs Graphics/GraphicsContextException.cs Graphics/GraphicsContextBase.cs Graphics/GraphicsBindingsBase.cs Graphics/ColorFormat.cs Graphics/OpenGL/GLDelegates.cs Graphics/OpenGL/GLHelper.cs Graphics/OpenGL/GLEnums.cs Graphics/OpenGL/GLCore.cs Graphics/OpenGL/GL.cs Graphics/OpenGL/ErrorHelper.cs Graphics/ES10/ES.cs Graphics/ES10/Enums.cs Graphics/ES10/ErrorHelper.cs Graphics/ES10/Helper.cs Graphics/ES10/Delegates.cs Graphics/ES10/Core.cs Graphics/ES11/ES.cs Graphics/ES11/Enums.cs Graphics/ES11/ErrorHelper.cs Graphics/ES11/Helper.cs Graphics/ES11/Delegates.cs Graphics/ES11/Core.cs Graphics/ES20/ES.cs Graphics/ES20/Enums.cs Graphics/ES20/ErrorHelper.cs Graphics/ES20/Helper.cs Graphics/ES20/Delegates.cs Graphics/ES20/Core.cs Input/Keyboard.cs Input/GamePad.cs Input/MouseDevice.cs Input/Key.cs Input/IJoystickDriver.cs Input/IMouseDriver.cs Input/IInputDriver.cs Input/KeyboardDevice.cs Input/KeyboardState.cs Input/MouseButton.cs Input/JoystickDevice.cs Input/IKeyboardDriver.cs Input/KeyboardKeyEventArgs.cs Input/Mouse.cs Input/MouseState.cs Input/GamePadState.cs Input/IInputDevice.cs Math/Quaternion.cs Math/Matrix3d.cs Math/Vector4.cs Math/BezierCurve.cs Math/Vector3.cs Math/Functions.cs Math/Matrix4d.cs Math/Vector2d.cs Math/Vector2h.cs Math/Vector3h.cs Math/Point.cs Math/Box2.cs Math/Matrix4.cs Math/Half.cs Math/Vector4d.cs Math/Rectangle.cs Math/Vector2.cs Math/BezierCurveQuadric.cs Math/MathHelper.cs Math/Quaterniond.cs Math/Vector4h.cs Math/Size.cs Math/Vector3d.cs Math/BezierCurveCubic.cs Compute/Memory.cs Compute/Device.cs Compute/Platform.cs Compute/Sampler.cs Compute/Kernel.cs Compute/Profiler.cs Compute/Program.cs Compute/Enums.cs Compute/CommandQueue.cs Compute/CLHelper.cs Compute/Event.cs Compute/Structs.cs Compute/Configuration.cs Compute/ComputeContext.cs Compute/CL10/Enums.cs Compute/CL10/ErrorHelper.cs Compute/CL10/Delegates.cs Compute/CL10/Core.cs Compute/CL10/CLHelper.cs Compute/CL10/CL.cs Compute/CL10/ImageFormat.cs Audio/AudioDeviceException.cs Audio/AudioContextException.cs Audio/AudioValueException.cs Audio/AudioException.cs Audio/AudioDeviceEnumerator.cs Audio/AudioDeviceErrorChecker.cs Audio/AudioContext.cs Audio/AudioCapture.cs Audio/OpenAL/Alc/AlcEnums.cs Audio/OpenAL/Alc/Alc.cs Audio/OpenAL/AL/EffectsExtensionPresets.cs Audio/OpenAL/AL/EffectsExtensionEnums.cs Audio/OpenAL/AL/XRamExtension.cs Audio/OpenAL/AL/EffectsExtension.cs Audio/OpenAL/AL/AL.cs Audio/OpenAL/AL/ALEnums.cs Properties/Resources.Designer.cs Platform/X11/X11Keyboard.cs Platform/X11/X11Mouse.cs Input/ButtonState.cs Platform/X11/XI2Mouse.cs Platform/MacOS/HIDInput.cs IntPtrEqualityComparer.cs /target:library /unsafe+ /define:"TRACE;DEBUG;EXPERIMENTAL" /doc:OpenTK.xml /nostdlib /reference:/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll /reference:/usr/lib/mono/gac/System.Data/4.0.0.0__b77a5c561934e089/System.Data.dll /reference:/usr/lib/mono/gac/System.Drawing/4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll /reference:/usr/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll /warn:4
DisplayDevice.cs(79): warning CS1030: #warning: `"Consolidate current resolution with bounds? Can they fall out of sync right now?"'
Platform/Windows/WinGLNative.cs(579): warning CS1030: #warning: `"This seems to resize one of the 'large' icons, rather than using a small icon directly (multi-icon files). Investigate!"'
Platform/Windows/WinGLContext.cs(95): warning CS1030: #warning: `"This is not entirely correct: Embedded is not a valid flag! We need to add a GetARBContextFlags(GraphicsContextFlags) method."'
Platform/Windows/WinMMJoystick.cs(118): warning CS1030: #warning: `"Implement joystick name detection for WinMM."'
Platform/X11/X11GLContext.cs(123): warning CS1030: #warning: `"This is not entirely correct: Embedded is not a valid flag! We need to add a GetARBContextFlags(GraphicsContextFlags) method."'
CSC: error CS0518: The predefined type `System.Object' is not defined or imported
CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
CSC: error CS0518: The predefined type `System.Single' is not defined or imported
CSC: error CS0518: The predefined type `System.Double' is not defined or imported
CSC: error CS0518: The predefined type `System.Char' is not defined or imported
CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
CSC: error CS0518: The predefined type `System.String' is not defined or imported
CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
CSC: error CS0518: The predefined type `System.Void' is not defined or imported
CSC: error CS0518: The predefined type `System.Array' is not defined or imported
CSC: error CS0518: The predefined type `System.Type' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.Exception' is not defined or imported
            Task "Csc" execution -- FAILED
            Done building target "CoreCompile" in project "/home/vedranm/workspace/HPC/scallion/opentk/Source/OpenTK/OpenTK.csproj".-- FAILED
        Done building project "/home/vedranm/workspace/HPC/scallion/opentk/Source/OpenTK/OpenTK.csproj".-- FAILED
        Project "/home/vedranm/workspace/HPC/scallion/openssl-net-0.5/ManagedOpenSsl/openssl.csproj" (default target(s)):
            Target PrepareForBuild:
                Configuration: Debug Platform: AnyCPU
            Target GenerateSatelliteAssemblies:
            No input files were specified for target GenerateSatelliteAssemblies, skipping.
            Target CoreCompile:
                Tool /usr/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:full /debug+ /optimize- /out:obj/Debug/openssl.dll /resource:obj/Debug/openssl.openssl.dll.config Core/Asn1DateTime.cs Core/Asn1Integer.cs Core/Asn1Object.cs Core/Asn1String.cs Core/Base.cs Core/BigNumber.cs Core/BIO.cs Core/Crypto.cs Core/MemoryTracker.cs Core/Native.cs Core/Objects.cs Core/OpenSslException.cs Core/Password.cs Core/Random.cs Core/Stack.cs Core/Version.cs Crypto/Cipher.cs Crypto/CryptoKey.cs Crypto/DH.cs Crypto/DSA.cs Crypto/EC/BuiltinCurve.cs Crypto/EC/DSASignature.cs Crypto/EC/Group.cs Crypto/EC/Key.cs Crypto/EC/Method.cs Crypto/EC/Point.cs Crypto/HMAC.cs Crypto/MessageDigest.cs Crypto/RSA.cs Properties/AssemblyInfo.cs SSL/Enums.cs SSL/Ssl.cs SSL/SslCipher.cs SSL/SslContext.cs SSL/SslMethod.cs SSL/SslStream.cs SSL/SslStreamBase.cs SSL/SslStreamClient.cs SSL/SslStreamServer.cs X509/Configuration.cs X509/Identity.cs X509/PKCS12.cs X509/PKCS7.cs X509/VerifyResult.cs X509/X509Certificate.cs X509/X509CertificateAuthority.cs X509/X509CertificateInfo.cs X509/X509Chain.cs X509/X509Extension.cs X509/X509Name.cs X509/X509Object.cs X509/X509Request.cs X509/X509Store.cs X509/X509StoreContext.cs /target:library /unsafe+ /define:"DEBUG;TRACE" /nostdlib /reference:/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll /reference:/usr/lib/mono/gac/System.Xml.Linq/4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll /reference:/usr/lib/mono/gac/System.Data.DataSetExtensions/4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll /reference:/usr/lib/mono/gac/System.Data/4.0.0.0__b77a5c561934e089/System.Data.dll /reference:/usr/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll /reference:/usr/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll /warn:4
CSC: error CS0518: The predefined type `System.Object' is not defined or imported
CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
CSC: error CS0518: The predefined type `System.Single' is not defined or imported
CSC: error CS0518: The predefined type `System.Double' is not defined or imported
CSC: error CS0518: The predefined type `System.Char' is not defined or imported
CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
CSC: error CS0518: The predefined type `System.String' is not defined or imported
CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
CSC: error CS0518: The predefined type `System.Void' is not defined or imported
CSC: error CS0518: The predefined type `System.Array' is not defined or imported
CSC: error CS0518: The predefined type `System.Type' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.Exception' is not defined or imported
            Task "Csc" execution -- FAILED
            Done building target "CoreCompile" in project "/home/vedranm/workspace/HPC/scallion/openssl-net-0.5/ManagedOpenSsl/openssl.csproj".-- FAILED
        Done building project "/home/vedranm/workspace/HPC/scallion/openssl-net-0.5/ManagedOpenSsl/openssl.csproj".-- FAILED
    Task "MSBuild" execution -- FAILED
    Done building target "Build" in project "/home/vedranm/workspace/HPC/scallion/scallion.sln".-- FAILED
Done building project "/home/vedranm/workspace/HPC/scallion/scallion.sln".-- FAILED

Build FAILED.

Warnings:

/home/vedranm/workspace/HPC/scallion/scallion.sln (default targets) ->
(Build target) ->
/home/vedranm/workspace/HPC/scallion/opentk/Source/OpenTK/OpenTK.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

    DisplayDevice.cs(79): warning CS1030: #warning: `"Consolidate current resolution with bounds? Can they fall out of sync right now?"'
    Platform/Windows/WinGLNative.cs(579): warning CS1030: #warning: `"This seems to resize one of the 'large' icons, rather than using a small icon directly (multi-icon files). Investigate!"'
    Platform/Windows/WinGLContext.cs(95): warning CS1030: #warning: `"This is not entirely correct: Embedded is not a valid flag! We need to add a GetARBContextFlags(GraphicsContextFlags) method."'
    Platform/Windows/WinMMJoystick.cs(118): warning CS1030: #warning: `"Implement joystick name detection for WinMM."'
    Platform/X11/X11GLContext.cs(123): warning CS1030: #warning: `"This is not entirely correct: Embedded is not a valid flag! We need to add a GetARBContextFlags(GraphicsContextFlags) method."'

Errors:

/home/vedranm/workspace/HPC/scallion/scallion.sln (default targets) ->
(Build target) ->
/home/vedranm/workspace/HPC/scallion/opentk/Source/OpenTK/OpenTK.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

    CSC: error CS0518: The predefined type `System.Object' is not defined or imported
    CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
    CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
    CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
    CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
    CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
    CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
    CSC: error CS0518: The predefined type `System.Single' is not defined or imported
    CSC: error CS0518: The predefined type `System.Double' is not defined or imported
    CSC: error CS0518: The predefined type `System.Char' is not defined or imported
    CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
    CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
    CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
    CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
    CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
    CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
    CSC: error CS0518: The predefined type `System.String' is not defined or imported
    CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
    CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
    CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
    CSC: error CS0518: The predefined type `System.Void' is not defined or imported
    CSC: error CS0518: The predefined type `System.Array' is not defined or imported
    CSC: error CS0518: The predefined type `System.Type' is not defined or imported
    CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
    CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
    CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
    CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
    CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
    CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
    CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
    CSC: error CS0518: The predefined type `System.Exception' is not defined or imported

/home/vedranm/workspace/HPC/scallion/scallion.sln (default targets) ->
(Build target) ->
/home/vedranm/workspace/HPC/scallion/openssl-net-0.5/ManagedOpenSsl/openssl.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

    CSC: error CS0518: The predefined type `System.Object' is not defined or imported
    CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
    CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
    CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
    CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
    CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
    CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
    CSC: error CS0518: The predefined type `System.Single' is not defined or imported
    CSC: error CS0518: The predefined type `System.Double' is not defined or imported
    CSC: error CS0518: The predefined type `System.Char' is not defined or imported
    CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
    CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
    CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
    CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
    CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
    CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
    CSC: error CS0518: The predefined type `System.String' is not defined or imported
    CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
    CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
    CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
    CSC: error CS0518: The predefined type `System.Void' is not defined or imported
    CSC: error CS0518: The predefined type `System.Array' is not defined or imported
    CSC: error CS0518: The predefined type `System.Type' is not defined or imported
    CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
    CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
    CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
    CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
    CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
    CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
    CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
    CSC: error CS0518: The predefined type `System.Exception' is not defined or imported

     5 Warning(s)
     62 Error(s)

Time Elapsed 00:00:07.5203940
```

I do have working OpenCL, and scallion builds and runs on the same system with Mono 3.2.8.

```
$ clinfo
Number of platforms                               1
  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 MESA 11.0.6
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA

  Platform Name                                   Clover
Number of devices                                 1
  Device Name                                     AMD CAICOS (DRM 2.43.0, LLVM 3.7.0)
  Device Vendor                                   AMD
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.1 MESA 11.0.6
  Driver Version                                  11.0.6
  Device OpenCL C Version                         OpenCL C 1.1 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Max compute units                               2
  Max clock frequency                             625MHz
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple              64
  Preferred / native vector sizes                 
    char                                                16 / 16      
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 0 / 0        (n/a)
    float                                                4 / 4       
    double                                               0 / 0        (n/a)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (n/a)
  Address bits                                    32, Little-Endian
  Global memory size                              1073741824 (1024MiB)
  Error Correction support                        No
  Max memory allocation                           268435456 (256MiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        None
  Image support                                   No
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Max constant buffer size                        268435456 (256MiB)
  Max number of constant args                     13
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Profiling timer resolution                      0ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
  Device Available                                Yes
  Compiler Available                              Yes
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Clover
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [MESA]
  clCreateContext(NULL, ...) [default]            Success [MESA]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 Clover
    Device Name                                   AMD CAICOS (DRM 2.43.0, LLVM 3.7.0)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Clover
    Device Name                                   AMD CAICOS (DRM 2.43.0, LLVM 3.7.0)

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.7
  ICD loader Profile                              OpenCL 1.2
```
